### ISSUE TITLE
Evaluate Monitor tool for live subprocess event streaming into agent context

### ISSUE THREAD

**Issue by robertsfeir** [robertsfeir/atelier-pipeline#43]
## What this is

Claude Code Monitor tool (April 2026) streams background script events into the conversation. Each stdout line from a background process becomes a notification the agent can react to live, rather than waiting for a command to complete and reading all output at once.

## Why for us

Several pipeline workflows today are effectively blind until a command finishes:

- **Colby dev-server startup.** Colby runs \`npm run dev\` in background and has no visibility into startup errors until he comes back later to check.
- **Roz E2E test runs.** Playwright outputs progress continuously; today Roz sees it all at the end in one blob. Streaming would let her react to failures as they happen.
- **Long-running builds.** Watching compilation errors appear rather than discovering them after a full build failure.
- **Log tails during debugging.** Following application logs in real time while exercising the feature.

## Tension

Monitor directly fights the \"silent success, verbose failure\" pattern from #31. A streaming log is verbose by definition. Signal-to-noise design matters:

- Filter at source (grep patterns, log levels) before streaming
- Cap lines per wave to avoid context flood
- Silence once the agent has the signal it needs

## Investigation goals

- [ ] Identify 2-3 workflows where Monitor would actually help (Roz E2E is the likely first).
- [ ] Design filter conventions: which log patterns reach the agent, which are dropped on the floor.
- [ ] Verify Monitor vs. \`Bash(run_in_background=true) + Read later\` — when does streaming win, when is polling fine?
- [ ] Measure context overhead per typical workflow.

## Risks

- Context flood if filters are weak.
- Monitor output can crowd out more-signal-dense inputs during long workflows.
- Nondeterministic — same run can produce different log orderings.

## Related

- Brain seed \`b086dd95\` — Monitor tool release notes
- Issue #31 — harness-engineering audit (silent-success tension)

## Acceptance

- [ ] Candidate workflow identified and pilot run completed
- [ ] Filter convention documented (what's signal, what's dropped)
- [ ] Decision: adopt for specific agents, adopt broadly, or decline

**Comment by robertsfeir** [comment]
**Closing as won't implement.**

The primary use case that motivated this issue — Roz streaming Playwright E2E test output in real time — is doubly stale: Roz no longer exists in the pipeline (replaced by Poirot, a blind diff reviewer), and ADR-0039 banned Playwright as an absolute constraint.

The remaining use cases (Colby dev-server startup visibility, log tails during debugging) are legitimate but don't clear the bar for a dedicated Monitor integration. Those workflows are already handled by `Bash(run_in_background=true)` + periodic read, which is simpler and doesn't risk context flood. The signal-to-noise design work this issue correctly identified as necessary would cost more than the benefit for the cases that remain.

If a specific workflow emerges where streaming genuinely outperforms polling, it can be re-evaluated then with a concrete example.
